---
#appICE Dashboard setup with gitpath and understand setup Process
#installing redis servide
- name: update apt
  apt: update_cache=yes

- name: install redis-server
  apt: name=redis-server state=latest

- name: edit the config file and change to supervised no to systemd
  lineinfile:
     path: /etc/redis/redis.conf
     # the string to search
     regexp: "supervised no"
     # replace with systemd
     line: "supervised systemd"
     state: present
     backup: yes

- name: restart the service
  service: name=redis.service state=restarted 

- name: password set
  lineinfile:
     path: /etc/redis/redis.conf
     # the string to search
     regexp: "# requirepass foobared"
     # replace with systemd
     line: "requirepass foobared"
     state: present
     backup: yes

- name: restart the service
  service: name=redis.service state=restarted

- name: rename the config command to asc12_config
  lineinfile:
     path: /etc/redis/redis.conf
     # searching the line
     regexp: '# rename-command CONFIG "" '
     insertbefore: '# Please note that changing the name of commands that are logged into the'
     # line to add
     line: "rename-command SHUTDOWN SHUTDOWN_MENOT"
     state: present
     backup: yes

- name: rename the config command to asc12_config
  lineinfile:
     path: /etc/redis/redis.conf
     # searching the line
     regexp: 'rename-command SHUTDOWN SHUTDOWN_MENOT '
     insertbefore: '# Please note that changing the name of commands that are logged into the'
     # line to add
     line: "rename-command CONFIG ASC12_CONFIG"
     state: present
     backup: yes

- name: increase a maxconnect
  lineinfile:
     path: /etc/redis/redis.conf
     # the string to search
     regexp: "# maxclients 10000"
     # replace with systemd
     line: "maxclients 20000"
     state: present
     backup: yes

- name: restart the service
  service: name=redis.service state=restarted
